# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  authapi:
    image: authapi
    build:
      context: .
      dockerfile: authApi/Dockerfile
    ports:
      - 50001:50001
